### ISSUE TITLE
Conflict when starting Koin on the Host App

### ISSUE THREAD

**Issue by epalaciosdr** [Digita1Reef/Siprocal-SDK-Example#2]
FATAL EXCEPTION: main (Ask Gemini)
Process: com.siprocal.sdkexample, PID: 1826
java.lang.RuntimeException: Unable to create application com.siprocal.sdkexample.MainApplication: org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
at android.app.ActivityThread.access$1300(ActivityThread.java:219)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started
at org.koin.core.context.GlobalContext.register(GlobalContext.kt:44)
at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:63)
at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:40)
at com.siprocal.sdk.client.SiprocalSDK.init(SourceFile:2)
at com.siprocal.sdkexample.MainApplication.onCreate(MainApplication.kt:17)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
at android.app.ActivityThread.access$1300(ActivityThread.java:219)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by epalaciosdr** [comment]
It is necessary to request that the client always include `androidContext(this@MyApplication)` during Koin initialization.
